version: '3.8'

services:
  my5gcore-ue:
    container_name: non3gpp1-scenary02
    build:
      context: ../../containers/nf_ue
      args:
        DEBUG_TOOLS: "true"
    volumes: 
      - ../../samples/iotsgdw/config:/my5gcore/config
      - ../../samples/iotsgdw/config/ipsec:/my5gcore/ipsec
      - ../../samples/iotsgdw/config/debug.sh:/my5gcore/debug.sh
      - ../../bin/runner.sh:/my5gcore/init.sh
      - ./volumes/metrics:/metrics
    environment:
      GIN_MODE: release
      DEBUG: "true"
      My5GC_MODULE : "ue1"
      NETSERVER: 10.100.120.10
      NUMDEV: ${DEVS_NUMBERS}
      PACKET: 1000
    extra_hosts:
      - "ue:192.168.127.2"
      - "n3iwf:192.168.127.1"
    networks:
      scenary2_5gcorenetwork:
       aliases:
         - ue.my5Gcore.org
    cap_add:
      - ALL
    #command: sh -c "./init.sh StartupUe 10.100.120.10"
    #command: sh -c "while :; do echo 'Hit CTRL+C'; sleep 1; done" 
    command: sh -c "./ipsec --ue ue --n3iwf n3iwf && ./debug.sh && ./init.sh StartupUe && ./bin/ue "
  
volumes:
   metrics:
 
networks:
  scenary2_5gcorenetwork:
     external: true
